### ISSUE TITLE
How to train dualcoop based on this repo?

### ISSUE THREAD

**Issue by RunDevil-Run** [guozix/TaI-DPT#1]
Interesting work! 
I‘m trying to reproduce this work as well as dualcoop baseline, could you tell me where I should modify to train the original dualcoop based on this repo? I notice that some configs missing like 'voc2007_partial.yaml'. 
Looking forward to your reply. Appreciate !!

**Comment by guozix** [comment]
Hope you are doing well!
Thanks for your interest in our paper. Current version of the code on GitHub page only covers the data preparation of TaI-DPT and the reproduction of basic results in Table 1. I will sort out and upload all the codes including the reproduction of DualCoOp in the next few days.

> Interesting work! I‘m trying to reproduce this work as well as dualcoop baseline, could you tell me where I should modify to train the original dualcoop based on this repo? I notice that some configs missing like 'voc2007_partial.yaml'. Looking forward to your reply. Appreciate !!

**Comment by Duojun-Huang** [comment]
Thanks for the instructive work. But where is the definition of evaluator "MLClassification", which is required in cfg.TEST.EVALUATOR?

**Comment by RunDevil-Run** [comment]
> Thanks for the instructive work. But where is the definition of evaluator "MLClassification", which is required in cfg.TEST.EVALUATOR?

TaI-DPT/Dassl.pytorch-master/dassl/evaluation/evaluator.py

**Comment by RunDevil-Run** [comment]
> Hope you are doing well! Thanks for your interest in our paper. Current version of the code on GitHub page only covers the data preparation of TaI-DPT and the reproduction of basic results in Table 1. I will sort out and upload all the codes including the reproduction of DualCoOp in the next few days.
> 
> > Interesting work! I‘m trying to reproduce this work as well as dualcoop baseline, could you tell me where I should modify to train the original dualcoop based on this repo? I notice that some configs missing like 'voc2007_partial.yaml'. Looking forward to your reply. Appreciate !!

Hello author! I tried to reproduce the Dualcoop+TaI-DPT part by myself, and the performance drops compared to the paper. But I fail to locate the problem.  Would you mind providing the codes these days? Thank you very much! _(:зゝ∠)_

**Comment by guozix** [comment]
@RunDevil-Run  The code has been updated, and now you can try to reproduce DualCoOp and ensemble results.

**Comment by RunDevil-Run** [comment]
> 



> @RunDevil-Run The code has been updated, and now you can try to reproduce DualCoOp and ensemble results.

Appreciate!
