### ISSUE TITLE
Some questions about reproducing "DualCoOp"

### ISSUE THREAD

**Issue by iamxiaoyubei** [guozix/TaI-DPT#10]
Hi, zixian, I saw that the performace of reproducing DualCoOp(DualCoOp*) is better than that in the DualCoOp paper, as shown in the table below. 
<img width="1035" alt="image" src="https://github.com/guozix/TaI-DPT/assets/21981293/6b08c257-c685-49c7-a68b-b31ba302dbdd">

So want to use your DualCoOp* for customized data. However, I saw that you obtained the `output_g` during training forward(https://github.com/guozix/TaI-DPT/blob/1333ecaa32bfffb4f2eb916f5532afb88ac457fe/trainers/Caption_dual.py#L398) but did not use it in the `dualcoop_loss`(https://github.com/guozix/TaI-DPT/blob/1333ecaa32bfffb4f2eb916f5532afb88ac457fe/trainers/utils.py#L151). So I want to ask whether `output_g` will be used in training? Is the result of the DualCoOp* generated by the current code using the following command?
`bash main_dual.sh nuswide_partial rn101_nus end 16 True nuswide_partial_dualcoop_448_CSC_p0_1 0.1 2`

**Comment by guozix** [comment]
Yes, only `output` is used to compute ASL loss, according to the DualCoOp paper. Since the author of DualCoOp has released their code, I recommend you use the official implementation :)
