### ISSUE TITLE
Could you provide the training data (filtered captions)?

### ISSUE THREAD

**Issue by JarvisUSTC** [guozix/TaI-DPT#2]
Hi, I am so interested in your work and want to reproduce it. However the data directory structure is too complex, could you please provide the training data (filtered captions) for us directly?

**Comment by guozix** [comment]
After preparing the raw data according to https://github.com/guozix/TaI-DPT#datasets, it may take about dozens of minutes to produce the training data structure.

I uploaded a copy of cached filtered captions here, https://drive.google.com/file/d/1RXpaCC2E492GxnPIkyYvxFSIdqf-76wh/view?usp=sharing

Unzip and put all the files under the project root path should work well.

**Comment by JarvisUSTC** [comment]
Thanks! I will try it.
