### ISSUE TITLE
Where to get all datasets in DATAROOT directory? 

### ISSUE THREAD

**Issue by StarCharlie** [guozix/TaI-DPT#3]
Hello, I am also interested in reproducing your work, but I find it difficult to construct DATAROOT directory. Would you be kind enough to provide us DATAROOT directory directly or give us a guideline about where to download all your datasets? Thank you very much!

**Comment by guozix** [comment]
The multi-label classification datasets can be accessed from their official websites [VOC2007](http://host.robots.ox.ac.uk/pascal/VOC/voc2007/), [MSCOCO2014](https://cocodataset.org/#download) and [NUS-WIDE](https://lms.comp.nus.edu.sg/wp-content/uploads/2019/research/nuswide/NUS-WIDE.html). The raw images of NUS-WIDE can be accessed from https://pan.baidu.com/s/1Bj-7fdrZAvUJPqAKrUkbbQ  (verification code: s6oj).

For the OpenImages dataset, we only use the localized narratives of its "V6" version. The ~130MB jsonl file can be downloaded from the official [site](https://storage.googleapis.com/localized-narratives/annotations/open_images_train_v6_captions.jsonl).

**Comment by StarCharlie** [comment]
Thank you a lot!!!!
