### ISSUE TITLE
TaI code implementation is inconsistent with the paper? 

### ISSUE THREAD

**Issue by iamxiaoyubei** [guozix/TaI-DPT#9]
The code implementation is inconsistent with the paper? The input here should be text instead of images (Text as Image), but the code here uses images for training.
```
output, output_local, _, _ = self.model(None, image)
```
https://github.com/guozix/TaI-DPT/blob/1333ecaa32bfffb4f2eb916f5532afb88ac457fe/trainers/Caption_distill_double.py#L464C65-L464C65

**Comment by guozix** [comment]
Ah, it's an abuse of the variable name "image". See the definition of the model forward function [here](https://github.com/guozix/TaI-DPT/blob/1333ecaa32bfffb4f2eb916f5532afb88ac457fe/trainers/Caption_distill_double.py#L294). I call the forward function in different ways in [training](https://github.com/guozix/TaI-DPT/blob/1333ecaa32bfffb4f2eb916f5532afb88ac457fe/trainers/Caption_distill_double.py#L464C51-L464C51) and [testing](https://github.com/guozix/TaI-DPT/blob/1333ecaa32bfffb4f2eb916f5532afb88ac457fe/trainers/Caption_distill_double.py#L369).

**Comment by iamxiaoyubei** [comment]
So, during training, the `batch["img"]` obtained by the dataloader is text? and the `input` obtained during testing is images? This is a bit confusing. Can you refer to the corresponding data loading line in codes?
